// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod terracedb {

#[allow(unused_imports, dead_code)]
pub mod durable {

#[allow(unused_imports, dead_code)]
pub mod backup_gc {


pub enum BackupGcBirthRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BackupGcBirthRecord<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BackupGcBirthRecord<'a> {
  type Inner = BackupGcBirthRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BackupGcBirthRecord<'a> {
  pub const VT_FORMAT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_OBJECT_KEY: ::flatbuffers::VOffsetT = 6;
  pub const VT_FIRST_UPLOADED_AT_MILLIS: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BackupGcBirthRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BackupGcBirthRecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BackupGcBirthRecord<'bldr>> {
    let mut builder = BackupGcBirthRecordBuilder::new(_fbb);
    builder.add_first_uploaded_at_millis(args.first_uploaded_at_millis);
    if let Some(x) = args.object_key { builder.add_object_key(x); }
    builder.add_format_version(args.format_version);
    builder.finish()
  }


  #[inline]
  pub fn format_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(BackupGcBirthRecord::VT_FORMAT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn object_key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(BackupGcBirthRecord::VT_OBJECT_KEY, None).unwrap()}
  }
  #[inline]
  pub fn first_uploaded_at_millis(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(BackupGcBirthRecord::VT_FIRST_UPLOADED_AT_MILLIS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for BackupGcBirthRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("format_version", Self::VT_FORMAT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("object_key", Self::VT_OBJECT_KEY, true)?
     .visit_field::<u64>("first_uploaded_at_millis", Self::VT_FIRST_UPLOADED_AT_MILLIS, false)?
     .finish();
    Ok(())
  }
}
pub struct BackupGcBirthRecordArgs<'a> {
    pub format_version: u32,
    pub object_key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub first_uploaded_at_millis: u64,
}
impl<'a> Default for BackupGcBirthRecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    BackupGcBirthRecordArgs {
      format_version: 0,
      object_key: None, // required field
      first_uploaded_at_millis: 0,
    }
  }
}

pub struct BackupGcBirthRecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BackupGcBirthRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_format_version(&mut self, format_version: u32) {
    self.fbb_.push_slot::<u32>(BackupGcBirthRecord::VT_FORMAT_VERSION, format_version, 0);
  }
  #[inline]
  pub fn add_object_key(&mut self, object_key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BackupGcBirthRecord::VT_OBJECT_KEY, object_key);
  }
  #[inline]
  pub fn add_first_uploaded_at_millis(&mut self, first_uploaded_at_millis: u64) {
    self.fbb_.push_slot::<u64>(BackupGcBirthRecord::VT_FIRST_UPLOADED_AT_MILLIS, first_uploaded_at_millis, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BackupGcBirthRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BackupGcBirthRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BackupGcBirthRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, BackupGcBirthRecord::VT_OBJECT_KEY,"object_key");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BackupGcBirthRecord<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BackupGcBirthRecord");
      ds.field("format_version", &self.format_version());
      ds.field("object_key", &self.object_key());
      ds.field("first_uploaded_at_millis", &self.first_uploaded_at_millis());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `BackupGcBirthRecord`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_backup_gc_birth_record_unchecked`.
pub fn root_as_backup_gc_birth_record(buf: &[u8]) -> Result<BackupGcBirthRecord<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<BackupGcBirthRecord>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `BackupGcBirthRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_backup_gc_birth_record_unchecked`.
pub fn size_prefixed_root_as_backup_gc_birth_record(buf: &[u8]) -> Result<BackupGcBirthRecord<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<BackupGcBirthRecord>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `BackupGcBirthRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_backup_gc_birth_record_unchecked`.
pub fn root_as_backup_gc_birth_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BackupGcBirthRecord<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<BackupGcBirthRecord<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `BackupGcBirthRecord` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_backup_gc_birth_record_unchecked`.
pub fn size_prefixed_root_as_backup_gc_birth_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BackupGcBirthRecord<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<BackupGcBirthRecord<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a BackupGcBirthRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `BackupGcBirthRecord`.
pub unsafe fn root_as_backup_gc_birth_record_unchecked(buf: &[u8]) -> BackupGcBirthRecord<'_> {
  unsafe { ::flatbuffers::root_unchecked::<BackupGcBirthRecord>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed BackupGcBirthRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `BackupGcBirthRecord`.
pub unsafe fn size_prefixed_root_as_backup_gc_birth_record_unchecked(buf: &[u8]) -> BackupGcBirthRecord<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<BackupGcBirthRecord>(buf) }
}
pub const BACKUP_GC_BIRTH_RECORD_IDENTIFIER: &str = "TDBG";

#[inline]
pub fn backup_gc_birth_record_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, BACKUP_GC_BIRTH_RECORD_IDENTIFIER, false)
}

#[inline]
pub fn backup_gc_birth_record_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, BACKUP_GC_BIRTH_RECORD_IDENTIFIER, true)
}

#[inline]
pub fn finish_backup_gc_birth_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<BackupGcBirthRecord<'a>>) {
  fbb.finish(root, Some(BACKUP_GC_BIRTH_RECORD_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_backup_gc_birth_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<BackupGcBirthRecord<'a>>) {
  fbb.finish_size_prefixed(root, Some(BACKUP_GC_BIRTH_RECORD_IDENTIFIER));
}
}  // pub mod backup_gc
}  // pub mod durable
}  // pub mod terracedb

