// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod terracedb {

#[allow(unused_imports, dead_code)]
pub mod durable {

#[allow(unused_imports, dead_code)]
pub mod catalog {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TABLE_FORMAT_TAG: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TABLE_FORMAT_TAG: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TABLE_FORMAT_TAG: [TableFormatTag; 3] = [
  TableFormatTag::None,
  TableFormatTag::Row,
  TableFormatTag::Columnar,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct TableFormatTag(pub u8);
#[allow(non_upper_case_globals)]
impl TableFormatTag {
  pub const None: Self = Self(0);
  pub const Row: Self = Self(1);
  pub const Columnar: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Row,
    Self::Columnar,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Row => Some("Row"),
      Self::Columnar => Some("Columnar"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for TableFormatTag {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for TableFormatTag {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for TableFormatTag {
    type Output = TableFormatTag;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for TableFormatTag {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for TableFormatTag {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for TableFormatTag {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_COMPACTION_STRATEGY_TAG: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_COMPACTION_STRATEGY_TAG: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_COMPACTION_STRATEGY_TAG: [CompactionStrategyTag; 4] = [
  CompactionStrategyTag::None,
  CompactionStrategyTag::Leveled,
  CompactionStrategyTag::Tiered,
  CompactionStrategyTag::Fifo,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CompactionStrategyTag(pub u8);
#[allow(non_upper_case_globals)]
impl CompactionStrategyTag {
  pub const None: Self = Self(0);
  pub const Leveled: Self = Self(1);
  pub const Tiered: Self = Self(2);
  pub const Fifo: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Leveled,
    Self::Tiered,
    Self::Fifo,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Leveled => Some("Leveled"),
      Self::Tiered => Some("Tiered"),
      Self::Fifo => Some("Fifo"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for CompactionStrategyTag {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for CompactionStrategyTag {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for CompactionStrategyTag {
    type Output = CompactionStrategyTag;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for CompactionStrategyTag {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for CompactionStrategyTag {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for CompactionStrategyTag {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FIELD_TYPE_TAG: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FIELD_TYPE_TAG: u8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FIELD_TYPE_TAG: [FieldTypeTag; 6] = [
  FieldTypeTag::None,
  FieldTypeTag::Int64,
  FieldTypeTag::Float64,
  FieldTypeTag::String,
  FieldTypeTag::Bytes,
  FieldTypeTag::Bool,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FieldTypeTag(pub u8);
#[allow(non_upper_case_globals)]
impl FieldTypeTag {
  pub const None: Self = Self(0);
  pub const Int64: Self = Self(1);
  pub const Float64: Self = Self(2);
  pub const String: Self = Self(3);
  pub const Bytes: Self = Self(4);
  pub const Bool: Self = Self(5);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Int64,
    Self::Float64,
    Self::String,
    Self::Bytes,
    Self::Bool,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Int64 => Some("Int64"),
      Self::Float64 => Some("Float64"),
      Self::String => Some("String"),
      Self::Bytes => Some("Bytes"),
      Self::Bool => Some("Bool"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for FieldTypeTag {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for FieldTypeTag {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for FieldTypeTag {
    type Output = FieldTypeTag;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for FieldTypeTag {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for FieldTypeTag {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for FieldTypeTag {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FIELD_VALUE_KIND: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FIELD_VALUE_KIND: u8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FIELD_VALUE_KIND: [FieldValueKind; 7] = [
  FieldValueKind::None,
  FieldValueKind::Null,
  FieldValueKind::Int64,
  FieldValueKind::Float64,
  FieldValueKind::String,
  FieldValueKind::Bytes,
  FieldValueKind::Bool,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FieldValueKind(pub u8);
#[allow(non_upper_case_globals)]
impl FieldValueKind {
  pub const None: Self = Self(0);
  pub const Null: Self = Self(1);
  pub const Int64: Self = Self(2);
  pub const Float64: Self = Self(3);
  pub const String: Self = Self(4);
  pub const Bytes: Self = Self(5);
  pub const Bool: Self = Self(6);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Null,
    Self::Int64,
    Self::Float64,
    Self::String,
    Self::Bytes,
    Self::Bool,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Null => Some("Null"),
      Self::Int64 => Some("Int64"),
      Self::Float64 => Some("Float64"),
      Self::String => Some("String"),
      Self::Bytes => Some("Bytes"),
      Self::Bool => Some("Bool"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for FieldValueKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for FieldValueKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for FieldValueKind {
    type Output = FieldValueKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for FieldValueKind {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for FieldValueKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for FieldValueKind {}
pub enum MetadataEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MetadataEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for MetadataEntry<'a> {
  type Inner = MetadataEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MetadataEntry<'a> {
  pub const VT_KEY: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE_JSON: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    MetadataEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MetadataEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<MetadataEntry<'bldr>> {
    let mut builder = MetadataEntryBuilder::new(_fbb);
    if let Some(x) = args.value_json { builder.add_value_json(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(MetadataEntry::VT_KEY, None).unwrap()}
  }
  #[inline]
  pub fn value_json(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(MetadataEntry::VT_VALUE_JSON, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for MetadataEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("value_json", Self::VT_VALUE_JSON, true)?
     .finish();
    Ok(())
  }
}
pub struct MetadataEntryArgs<'a> {
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub value_json: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for MetadataEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    MetadataEntryArgs {
      key: None, // required field
      value_json: None, // required field
    }
  }
}

pub struct MetadataEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MetadataEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MetadataEntry::VT_KEY, key);
  }
  #[inline]
  pub fn add_value_json(&mut self, value_json: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MetadataEntry::VT_VALUE_JSON, value_json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MetadataEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MetadataEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<MetadataEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, MetadataEntry::VT_KEY,"key");
    self.fbb_.required(o, MetadataEntry::VT_VALUE_JSON,"value_json");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for MetadataEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("MetadataEntry");
      ds.field("key", &self.key());
      ds.field("value_json", &self.value_json());
      ds.finish()
  }
}
pub enum FieldValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FieldValue<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FieldValue<'a> {
  type Inner = FieldValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FieldValue<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_I64_VALUE: ::flatbuffers::VOffsetT = 6;
  pub const VT_F64_VALUE: ::flatbuffers::VOffsetT = 8;
  pub const VT_STRING_VALUE: ::flatbuffers::VOffsetT = 10;
  pub const VT_BYTES_VALUE: ::flatbuffers::VOffsetT = 12;
  pub const VT_BOOL_VALUE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FieldValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FieldValueArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FieldValue<'bldr>> {
    let mut builder = FieldValueBuilder::new(_fbb);
    builder.add_f64_value(args.f64_value);
    builder.add_i64_value(args.i64_value);
    if let Some(x) = args.bytes_value { builder.add_bytes_value(x); }
    if let Some(x) = args.string_value { builder.add_string_value(x); }
    builder.add_bool_value(args.bool_value);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> FieldValueKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FieldValueKind>(FieldValue::VT_KIND, Some(FieldValueKind::None)).unwrap()}
  }
  #[inline]
  pub fn i64_value(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(FieldValue::VT_I64_VALUE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn f64_value(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(FieldValue::VT_F64_VALUE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn string_value(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FieldValue::VT_STRING_VALUE, None)}
  }
  #[inline]
  pub fn bytes_value(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(FieldValue::VT_BYTES_VALUE, None)}
  }
  #[inline]
  pub fn bool_value(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(FieldValue::VT_BOOL_VALUE, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for FieldValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<FieldValueKind>("kind", Self::VT_KIND, false)?
     .visit_field::<i64>("i64_value", Self::VT_I64_VALUE, false)?
     .visit_field::<f64>("f64_value", Self::VT_F64_VALUE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("string_value", Self::VT_STRING_VALUE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("bytes_value", Self::VT_BYTES_VALUE, false)?
     .visit_field::<bool>("bool_value", Self::VT_BOOL_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct FieldValueArgs<'a> {
    pub kind: FieldValueKind,
    pub i64_value: i64,
    pub f64_value: f64,
    pub string_value: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub bytes_value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub bool_value: bool,
}
impl<'a> Default for FieldValueArgs<'a> {
  #[inline]
  fn default() -> Self {
    FieldValueArgs {
      kind: FieldValueKind::None,
      i64_value: 0,
      f64_value: 0.0,
      string_value: None,
      bytes_value: None,
      bool_value: false,
    }
  }
}

pub struct FieldValueBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FieldValueBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: FieldValueKind) {
    self.fbb_.push_slot::<FieldValueKind>(FieldValue::VT_KIND, kind, FieldValueKind::None);
  }
  #[inline]
  pub fn add_i64_value(&mut self, i64_value: i64) {
    self.fbb_.push_slot::<i64>(FieldValue::VT_I64_VALUE, i64_value, 0);
  }
  #[inline]
  pub fn add_f64_value(&mut self, f64_value: f64) {
    self.fbb_.push_slot::<f64>(FieldValue::VT_F64_VALUE, f64_value, 0.0);
  }
  #[inline]
  pub fn add_string_value(&mut self, string_value: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FieldValue::VT_STRING_VALUE, string_value);
  }
  #[inline]
  pub fn add_bytes_value(&mut self, bytes_value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FieldValue::VT_BYTES_VALUE, bytes_value);
  }
  #[inline]
  pub fn add_bool_value(&mut self, bool_value: bool) {
    self.fbb_.push_slot::<bool>(FieldValue::VT_BOOL_VALUE, bool_value, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FieldValueBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FieldValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FieldValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FieldValue<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FieldValue");
      ds.field("kind", &self.kind());
      ds.field("i64_value", &self.i64_value());
      ds.field("f64_value", &self.f64_value());
      ds.field("string_value", &self.string_value());
      ds.field("bytes_value", &self.bytes_value());
      ds.field("bool_value", &self.bool_value());
      ds.finish()
  }
}
pub enum FieldDefinitionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FieldDefinition<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FieldDefinition<'a> {
  type Inner = FieldDefinition<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FieldDefinition<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_FIELD_TYPE: ::flatbuffers::VOffsetT = 8;
  pub const VT_NULLABLE: ::flatbuffers::VOffsetT = 10;
  pub const VT_DEFAULT_VALUE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FieldDefinition { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FieldDefinitionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FieldDefinition<'bldr>> {
    let mut builder = FieldDefinitionBuilder::new(_fbb);
    if let Some(x) = args.default_value { builder.add_default_value(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_nullable(args.nullable);
    builder.add_field_type(args.field_type);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(FieldDefinition::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FieldDefinition::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn field_type(&self) -> FieldTypeTag {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FieldTypeTag>(FieldDefinition::VT_FIELD_TYPE, Some(FieldTypeTag::None)).unwrap()}
  }
  #[inline]
  pub fn nullable(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(FieldDefinition::VT_NULLABLE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn default_value(&self) -> Option<FieldValue<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<FieldValue>>(FieldDefinition::VT_DEFAULT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for FieldDefinition<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("id", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<FieldTypeTag>("field_type", Self::VT_FIELD_TYPE, false)?
     .visit_field::<bool>("nullable", Self::VT_NULLABLE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<FieldValue>>("default_value", Self::VT_DEFAULT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct FieldDefinitionArgs<'a> {
    pub id: u32,
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub field_type: FieldTypeTag,
    pub nullable: bool,
    pub default_value: Option<::flatbuffers::WIPOffset<FieldValue<'a>>>,
}
impl<'a> Default for FieldDefinitionArgs<'a> {
  #[inline]
  fn default() -> Self {
    FieldDefinitionArgs {
      id: 0,
      name: None, // required field
      field_type: FieldTypeTag::None,
      nullable: false,
      default_value: None,
    }
  }
}

pub struct FieldDefinitionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FieldDefinitionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u32) {
    self.fbb_.push_slot::<u32>(FieldDefinition::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FieldDefinition::VT_NAME, name);
  }
  #[inline]
  pub fn add_field_type(&mut self, field_type: FieldTypeTag) {
    self.fbb_.push_slot::<FieldTypeTag>(FieldDefinition::VT_FIELD_TYPE, field_type, FieldTypeTag::None);
  }
  #[inline]
  pub fn add_nullable(&mut self, nullable: bool) {
    self.fbb_.push_slot::<bool>(FieldDefinition::VT_NULLABLE, nullable, false);
  }
  #[inline]
  pub fn add_default_value(&mut self, default_value: ::flatbuffers::WIPOffset<FieldValue<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<FieldValue>>(FieldDefinition::VT_DEFAULT_VALUE, default_value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FieldDefinitionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FieldDefinitionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FieldDefinition<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FieldDefinition::VT_NAME,"name");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FieldDefinition<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FieldDefinition");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("field_type", &self.field_type());
      ds.field("nullable", &self.nullable());
      ds.field("default_value", &self.default_value());
      ds.finish()
  }
}
pub enum SchemaDefinitionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SchemaDefinition<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SchemaDefinition<'a> {
  type Inner = SchemaDefinition<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SchemaDefinition<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_FIELDS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SchemaDefinition { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SchemaDefinitionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SchemaDefinition<'bldr>> {
    let mut builder = SchemaDefinitionBuilder::new(_fbb);
    if let Some(x) = args.fields { builder.add_fields(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SchemaDefinition::VT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn fields(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FieldDefinition<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FieldDefinition>>>>(SchemaDefinition::VT_FIELDS, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SchemaDefinition<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("version", Self::VT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<FieldDefinition>>>>("fields", Self::VT_FIELDS, true)?
     .finish();
    Ok(())
  }
}
pub struct SchemaDefinitionArgs<'a> {
    pub version: u32,
    pub fields: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FieldDefinition<'a>>>>>,
}
impl<'a> Default for SchemaDefinitionArgs<'a> {
  #[inline]
  fn default() -> Self {
    SchemaDefinitionArgs {
      version: 0,
      fields: None, // required field
    }
  }
}

pub struct SchemaDefinitionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SchemaDefinitionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(SchemaDefinition::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_fields(&mut self, fields: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<FieldDefinition<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SchemaDefinition::VT_FIELDS, fields);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SchemaDefinitionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SchemaDefinitionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SchemaDefinition<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, SchemaDefinition::VT_FIELDS,"fields");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SchemaDefinition<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SchemaDefinition");
      ds.field("version", &self.version());
      ds.field("fields", &self.fields());
      ds.finish()
  }
}
pub enum TableConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TableConfig<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for TableConfig<'a> {
  type Inner = TableConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TableConfig<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_FORMAT: ::flatbuffers::VOffsetT = 6;
  pub const VT_HAS_MAX_MERGE_OPERAND_CHAIN_LENGTH: ::flatbuffers::VOffsetT = 8;
  pub const VT_MAX_MERGE_OPERAND_CHAIN_LENGTH: ::flatbuffers::VOffsetT = 10;
  pub const VT_HAS_BLOOM_FILTER_BITS_PER_KEY: ::flatbuffers::VOffsetT = 12;
  pub const VT_BLOOM_FILTER_BITS_PER_KEY: ::flatbuffers::VOffsetT = 14;
  pub const VT_HAS_HISTORY_RETENTION_SEQUENCES: ::flatbuffers::VOffsetT = 16;
  pub const VT_HISTORY_RETENTION_SEQUENCES: ::flatbuffers::VOffsetT = 18;
  pub const VT_COMPACTION_STRATEGY: ::flatbuffers::VOffsetT = 20;
  pub const VT_SCHEMA: ::flatbuffers::VOffsetT = 22;
  pub const VT_METADATA_ENTRIES: ::flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    TableConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TableConfigArgs<'args>
  ) -> ::flatbuffers::WIPOffset<TableConfig<'bldr>> {
    let mut builder = TableConfigBuilder::new(_fbb);
    builder.add_history_retention_sequences(args.history_retention_sequences);
    if let Some(x) = args.metadata_entries { builder.add_metadata_entries(x); }
    if let Some(x) = args.schema { builder.add_schema(x); }
    builder.add_bloom_filter_bits_per_key(args.bloom_filter_bits_per_key);
    builder.add_max_merge_operand_chain_length(args.max_merge_operand_chain_length);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_compaction_strategy(args.compaction_strategy);
    builder.add_has_history_retention_sequences(args.has_history_retention_sequences);
    builder.add_has_bloom_filter_bits_per_key(args.has_bloom_filter_bits_per_key);
    builder.add_has_max_merge_operand_chain_length(args.has_max_merge_operand_chain_length);
    builder.add_format(args.format);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(TableConfig::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn format(&self) -> TableFormatTag {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TableFormatTag>(TableConfig::VT_FORMAT, Some(TableFormatTag::None)).unwrap()}
  }
  #[inline]
  pub fn has_max_merge_operand_chain_length(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(TableConfig::VT_HAS_MAX_MERGE_OPERAND_CHAIN_LENGTH, Some(false)).unwrap()}
  }
  #[inline]
  pub fn max_merge_operand_chain_length(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(TableConfig::VT_MAX_MERGE_OPERAND_CHAIN_LENGTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_bloom_filter_bits_per_key(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(TableConfig::VT_HAS_BLOOM_FILTER_BITS_PER_KEY, Some(false)).unwrap()}
  }
  #[inline]
  pub fn bloom_filter_bits_per_key(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(TableConfig::VT_BLOOM_FILTER_BITS_PER_KEY, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_history_retention_sequences(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(TableConfig::VT_HAS_HISTORY_RETENTION_SEQUENCES, Some(false)).unwrap()}
  }
  #[inline]
  pub fn history_retention_sequences(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TableConfig::VT_HISTORY_RETENTION_SEQUENCES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn compaction_strategy(&self) -> CompactionStrategyTag {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CompactionStrategyTag>(TableConfig::VT_COMPACTION_STRATEGY, Some(CompactionStrategyTag::None)).unwrap()}
  }
  #[inline]
  pub fn schema(&self) -> Option<SchemaDefinition<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SchemaDefinition>>(TableConfig::VT_SCHEMA, None)}
  }
  #[inline]
  pub fn metadata_entries(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MetadataEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MetadataEntry>>>>(TableConfig::VT_METADATA_ENTRIES, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for TableConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<TableFormatTag>("format", Self::VT_FORMAT, false)?
     .visit_field::<bool>("has_max_merge_operand_chain_length", Self::VT_HAS_MAX_MERGE_OPERAND_CHAIN_LENGTH, false)?
     .visit_field::<u32>("max_merge_operand_chain_length", Self::VT_MAX_MERGE_OPERAND_CHAIN_LENGTH, false)?
     .visit_field::<bool>("has_bloom_filter_bits_per_key", Self::VT_HAS_BLOOM_FILTER_BITS_PER_KEY, false)?
     .visit_field::<u32>("bloom_filter_bits_per_key", Self::VT_BLOOM_FILTER_BITS_PER_KEY, false)?
     .visit_field::<bool>("has_history_retention_sequences", Self::VT_HAS_HISTORY_RETENTION_SEQUENCES, false)?
     .visit_field::<u64>("history_retention_sequences", Self::VT_HISTORY_RETENTION_SEQUENCES, false)?
     .visit_field::<CompactionStrategyTag>("compaction_strategy", Self::VT_COMPACTION_STRATEGY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<SchemaDefinition>>("schema", Self::VT_SCHEMA, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<MetadataEntry>>>>("metadata_entries", Self::VT_METADATA_ENTRIES, true)?
     .finish();
    Ok(())
  }
}
pub struct TableConfigArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub format: TableFormatTag,
    pub has_max_merge_operand_chain_length: bool,
    pub max_merge_operand_chain_length: u32,
    pub has_bloom_filter_bits_per_key: bool,
    pub bloom_filter_bits_per_key: u32,
    pub has_history_retention_sequences: bool,
    pub history_retention_sequences: u64,
    pub compaction_strategy: CompactionStrategyTag,
    pub schema: Option<::flatbuffers::WIPOffset<SchemaDefinition<'a>>>,
    pub metadata_entries: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MetadataEntry<'a>>>>>,
}
impl<'a> Default for TableConfigArgs<'a> {
  #[inline]
  fn default() -> Self {
    TableConfigArgs {
      name: None, // required field
      format: TableFormatTag::None,
      has_max_merge_operand_chain_length: false,
      max_merge_operand_chain_length: 0,
      has_bloom_filter_bits_per_key: false,
      bloom_filter_bits_per_key: 0,
      has_history_retention_sequences: false,
      history_retention_sequences: 0,
      compaction_strategy: CompactionStrategyTag::None,
      schema: None,
      metadata_entries: None, // required field
    }
  }
}

pub struct TableConfigBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TableConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableConfig::VT_NAME, name);
  }
  #[inline]
  pub fn add_format(&mut self, format: TableFormatTag) {
    self.fbb_.push_slot::<TableFormatTag>(TableConfig::VT_FORMAT, format, TableFormatTag::None);
  }
  #[inline]
  pub fn add_has_max_merge_operand_chain_length(&mut self, has_max_merge_operand_chain_length: bool) {
    self.fbb_.push_slot::<bool>(TableConfig::VT_HAS_MAX_MERGE_OPERAND_CHAIN_LENGTH, has_max_merge_operand_chain_length, false);
  }
  #[inline]
  pub fn add_max_merge_operand_chain_length(&mut self, max_merge_operand_chain_length: u32) {
    self.fbb_.push_slot::<u32>(TableConfig::VT_MAX_MERGE_OPERAND_CHAIN_LENGTH, max_merge_operand_chain_length, 0);
  }
  #[inline]
  pub fn add_has_bloom_filter_bits_per_key(&mut self, has_bloom_filter_bits_per_key: bool) {
    self.fbb_.push_slot::<bool>(TableConfig::VT_HAS_BLOOM_FILTER_BITS_PER_KEY, has_bloom_filter_bits_per_key, false);
  }
  #[inline]
  pub fn add_bloom_filter_bits_per_key(&mut self, bloom_filter_bits_per_key: u32) {
    self.fbb_.push_slot::<u32>(TableConfig::VT_BLOOM_FILTER_BITS_PER_KEY, bloom_filter_bits_per_key, 0);
  }
  #[inline]
  pub fn add_has_history_retention_sequences(&mut self, has_history_retention_sequences: bool) {
    self.fbb_.push_slot::<bool>(TableConfig::VT_HAS_HISTORY_RETENTION_SEQUENCES, has_history_retention_sequences, false);
  }
  #[inline]
  pub fn add_history_retention_sequences(&mut self, history_retention_sequences: u64) {
    self.fbb_.push_slot::<u64>(TableConfig::VT_HISTORY_RETENTION_SEQUENCES, history_retention_sequences, 0);
  }
  #[inline]
  pub fn add_compaction_strategy(&mut self, compaction_strategy: CompactionStrategyTag) {
    self.fbb_.push_slot::<CompactionStrategyTag>(TableConfig::VT_COMPACTION_STRATEGY, compaction_strategy, CompactionStrategyTag::None);
  }
  #[inline]
  pub fn add_schema(&mut self, schema: ::flatbuffers::WIPOffset<SchemaDefinition<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<SchemaDefinition>>(TableConfig::VT_SCHEMA, schema);
  }
  #[inline]
  pub fn add_metadata_entries(&mut self, metadata_entries: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<MetadataEntry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TableConfig::VT_METADATA_ENTRIES, metadata_entries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TableConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TableConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<TableConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, TableConfig::VT_NAME,"name");
    self.fbb_.required(o, TableConfig::VT_METADATA_ENTRIES,"metadata_entries");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for TableConfig<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("TableConfig");
      ds.field("name", &self.name());
      ds.field("format", &self.format());
      ds.field("has_max_merge_operand_chain_length", &self.has_max_merge_operand_chain_length());
      ds.field("max_merge_operand_chain_length", &self.max_merge_operand_chain_length());
      ds.field("has_bloom_filter_bits_per_key", &self.has_bloom_filter_bits_per_key());
      ds.field("bloom_filter_bits_per_key", &self.bloom_filter_bits_per_key());
      ds.field("has_history_retention_sequences", &self.has_history_retention_sequences());
      ds.field("history_retention_sequences", &self.history_retention_sequences());
      ds.field("compaction_strategy", &self.compaction_strategy());
      ds.field("schema", &self.schema());
      ds.field("metadata_entries", &self.metadata_entries());
      ds.finish()
  }
}
pub enum CatalogEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CatalogEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CatalogEntry<'a> {
  type Inner = CatalogEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CatalogEntry<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_CONFIG: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CatalogEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CatalogEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<CatalogEntry<'bldr>> {
    let mut builder = CatalogEntryBuilder::new(_fbb);
    if let Some(x) = args.config { builder.add_config(x); }
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CatalogEntry::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn config(&self) -> TableConfig<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TableConfig>>(CatalogEntry::VT_CONFIG, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for CatalogEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("id", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<TableConfig>>("config", Self::VT_CONFIG, true)?
     .finish();
    Ok(())
  }
}
pub struct CatalogEntryArgs<'a> {
    pub id: u32,
    pub config: Option<::flatbuffers::WIPOffset<TableConfig<'a>>>,
}
impl<'a> Default for CatalogEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    CatalogEntryArgs {
      id: 0,
      config: None, // required field
    }
  }
}

pub struct CatalogEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CatalogEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u32) {
    self.fbb_.push_slot::<u32>(CatalogEntry::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_config(&mut self, config: ::flatbuffers::WIPOffset<TableConfig<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<TableConfig>>(CatalogEntry::VT_CONFIG, config);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CatalogEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CatalogEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CatalogEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, CatalogEntry::VT_CONFIG,"config");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CatalogEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CatalogEntry");
      ds.field("id", &self.id());
      ds.field("config", &self.config());
      ds.finish()
  }
}
pub enum CatalogOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Catalog<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Catalog<'a> {
  type Inner = Catalog<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Catalog<'a> {
  pub const VT_FORMAT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_TABLES: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Catalog { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CatalogArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Catalog<'bldr>> {
    let mut builder = CatalogBuilder::new(_fbb);
    if let Some(x) = args.tables { builder.add_tables(x); }
    builder.add_format_version(args.format_version);
    builder.finish()
  }


  #[inline]
  pub fn format_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Catalog::VT_FORMAT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tables(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CatalogEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CatalogEntry>>>>(Catalog::VT_TABLES, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Catalog<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("format_version", Self::VT_FORMAT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<CatalogEntry>>>>("tables", Self::VT_TABLES, true)?
     .finish();
    Ok(())
  }
}
pub struct CatalogArgs<'a> {
    pub format_version: u32,
    pub tables: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CatalogEntry<'a>>>>>,
}
impl<'a> Default for CatalogArgs<'a> {
  #[inline]
  fn default() -> Self {
    CatalogArgs {
      format_version: 0,
      tables: None, // required field
    }
  }
}

pub struct CatalogBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CatalogBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_format_version(&mut self, format_version: u32) {
    self.fbb_.push_slot::<u32>(Catalog::VT_FORMAT_VERSION, format_version, 0);
  }
  #[inline]
  pub fn add_tables(&mut self, tables: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<CatalogEntry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Catalog::VT_TABLES, tables);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CatalogBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CatalogBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Catalog<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Catalog::VT_TABLES,"tables");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Catalog<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Catalog");
      ds.field("format_version", &self.format_version());
      ds.field("tables", &self.tables());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Catalog`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_catalog_unchecked`.
pub fn root_as_catalog(buf: &[u8]) -> Result<Catalog<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Catalog>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Catalog` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_catalog_unchecked`.
pub fn size_prefixed_root_as_catalog(buf: &[u8]) -> Result<Catalog<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Catalog>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Catalog` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_catalog_unchecked`.
pub fn root_as_catalog_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Catalog<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Catalog<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Catalog` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_catalog_unchecked`.
pub fn size_prefixed_root_as_catalog_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Catalog<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Catalog<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Catalog and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Catalog`.
pub unsafe fn root_as_catalog_unchecked(buf: &[u8]) -> Catalog<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Catalog>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Catalog and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Catalog`.
pub unsafe fn size_prefixed_root_as_catalog_unchecked(buf: &[u8]) -> Catalog<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Catalog>(buf) }
}
pub const CATALOG_IDENTIFIER: &str = "TDBC";

#[inline]
pub fn catalog_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, CATALOG_IDENTIFIER, false)
}

#[inline]
pub fn catalog_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, CATALOG_IDENTIFIER, true)
}

#[inline]
pub fn finish_catalog_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Catalog<'a>>) {
  fbb.finish(root, Some(CATALOG_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_catalog_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Catalog<'a>>) {
  fbb.finish_size_prefixed(root, Some(CATALOG_IDENTIFIER));
}
}  // pub mod catalog
}  // pub mod durable
}  // pub mod terracedb

