// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod terracedb {

#[allow(unused_imports, dead_code)]
pub mod durable {

#[allow(unused_imports, dead_code)]
pub mod local_manifest {


pub enum ManifestSstableOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ManifestSstable<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ManifestSstable<'a> {
  type Inner = ManifestSstable<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ManifestSstable<'a> {
  pub const VT_TABLE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_LOCAL_ID: ::flatbuffers::VOffsetT = 8;
  pub const VT_FILE_PATH: ::flatbuffers::VOffsetT = 10;
  pub const VT_REMOTE_KEY: ::flatbuffers::VOffsetT = 12;
  pub const VT_LENGTH: ::flatbuffers::VOffsetT = 14;
  pub const VT_CHECKSUM: ::flatbuffers::VOffsetT = 16;
  pub const VT_DATA_CHECKSUM: ::flatbuffers::VOffsetT = 18;
  pub const VT_MIN_KEY: ::flatbuffers::VOffsetT = 20;
  pub const VT_MAX_KEY: ::flatbuffers::VOffsetT = 22;
  pub const VT_MIN_SEQUENCE: ::flatbuffers::VOffsetT = 24;
  pub const VT_MAX_SEQUENCE: ::flatbuffers::VOffsetT = 26;
  pub const VT_HAS_SCHEMA_VERSION: ::flatbuffers::VOffsetT = 28;
  pub const VT_SCHEMA_VERSION: ::flatbuffers::VOffsetT = 30;
  pub const VT_SHARD_OWNERSHIP_JSON: ::flatbuffers::VOffsetT = 32;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ManifestSstable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ManifestSstableArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ManifestSstable<'bldr>> {
    let mut builder = ManifestSstableBuilder::new(_fbb);
    builder.add_max_sequence(args.max_sequence);
    builder.add_min_sequence(args.min_sequence);
    builder.add_length(args.length);
    if let Some(x) = args.shard_ownership_json { builder.add_shard_ownership_json(x); }
    builder.add_schema_version(args.schema_version);
    if let Some(x) = args.max_key { builder.add_max_key(x); }
    if let Some(x) = args.min_key { builder.add_min_key(x); }
    builder.add_data_checksum(args.data_checksum);
    builder.add_checksum(args.checksum);
    if let Some(x) = args.remote_key { builder.add_remote_key(x); }
    if let Some(x) = args.file_path { builder.add_file_path(x); }
    if let Some(x) = args.local_id { builder.add_local_id(x); }
    builder.add_level(args.level);
    builder.add_table_id(args.table_id);
    builder.add_has_schema_version(args.has_schema_version);
    builder.finish()
  }


  #[inline]
  pub fn table_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestSstable::VT_TABLE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn level(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestSstable::VT_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn local_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ManifestSstable::VT_LOCAL_ID, None).unwrap()}
  }
  #[inline]
  pub fn file_path(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ManifestSstable::VT_FILE_PATH, None)}
  }
  #[inline]
  pub fn remote_key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ManifestSstable::VT_REMOTE_KEY, None)}
  }
  #[inline]
  pub fn length(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ManifestSstable::VT_LENGTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn checksum(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestSstable::VT_CHECKSUM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data_checksum(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestSstable::VT_DATA_CHECKSUM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn min_key(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ManifestSstable::VT_MIN_KEY, None).unwrap()}
  }
  #[inline]
  pub fn max_key(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ManifestSstable::VT_MAX_KEY, None).unwrap()}
  }
  #[inline]
  pub fn min_sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ManifestSstable::VT_MIN_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ManifestSstable::VT_MAX_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_schema_version(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ManifestSstable::VT_HAS_SCHEMA_VERSION, Some(false)).unwrap()}
  }
  #[inline]
  pub fn schema_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestSstable::VT_SCHEMA_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn shard_ownership_json(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ManifestSstable::VT_SHARD_OWNERSHIP_JSON, None)}
  }
}

impl ::flatbuffers::Verifiable for ManifestSstable<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("table_id", Self::VT_TABLE_ID, false)?
     .visit_field::<u32>("level", Self::VT_LEVEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("local_id", Self::VT_LOCAL_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("file_path", Self::VT_FILE_PATH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("remote_key", Self::VT_REMOTE_KEY, false)?
     .visit_field::<u64>("length", Self::VT_LENGTH, false)?
     .visit_field::<u32>("checksum", Self::VT_CHECKSUM, false)?
     .visit_field::<u32>("data_checksum", Self::VT_DATA_CHECKSUM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("min_key", Self::VT_MIN_KEY, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("max_key", Self::VT_MAX_KEY, true)?
     .visit_field::<u64>("min_sequence", Self::VT_MIN_SEQUENCE, false)?
     .visit_field::<u64>("max_sequence", Self::VT_MAX_SEQUENCE, false)?
     .visit_field::<bool>("has_schema_version", Self::VT_HAS_SCHEMA_VERSION, false)?
     .visit_field::<u32>("schema_version", Self::VT_SCHEMA_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("shard_ownership_json", Self::VT_SHARD_OWNERSHIP_JSON, false)?
     .finish();
    Ok(())
  }
}
pub struct ManifestSstableArgs<'a> {
    pub table_id: u32,
    pub level: u32,
    pub local_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub file_path: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub remote_key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub length: u64,
    pub checksum: u32,
    pub data_checksum: u32,
    pub min_key: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub max_key: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub min_sequence: u64,
    pub max_sequence: u64,
    pub has_schema_version: bool,
    pub schema_version: u32,
    pub shard_ownership_json: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ManifestSstableArgs<'a> {
  #[inline]
  fn default() -> Self {
    ManifestSstableArgs {
      table_id: 0,
      level: 0,
      local_id: None, // required field
      file_path: None,
      remote_key: None,
      length: 0,
      checksum: 0,
      data_checksum: 0,
      min_key: None, // required field
      max_key: None, // required field
      min_sequence: 0,
      max_sequence: 0,
      has_schema_version: false,
      schema_version: 0,
      shard_ownership_json: None,
    }
  }
}

pub struct ManifestSstableBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ManifestSstableBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_table_id(&mut self, table_id: u32) {
    self.fbb_.push_slot::<u32>(ManifestSstable::VT_TABLE_ID, table_id, 0);
  }
  #[inline]
  pub fn add_level(&mut self, level: u32) {
    self.fbb_.push_slot::<u32>(ManifestSstable::VT_LEVEL, level, 0);
  }
  #[inline]
  pub fn add_local_id(&mut self, local_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_LOCAL_ID, local_id);
  }
  #[inline]
  pub fn add_file_path(&mut self, file_path: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_FILE_PATH, file_path);
  }
  #[inline]
  pub fn add_remote_key(&mut self, remote_key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_REMOTE_KEY, remote_key);
  }
  #[inline]
  pub fn add_length(&mut self, length: u64) {
    self.fbb_.push_slot::<u64>(ManifestSstable::VT_LENGTH, length, 0);
  }
  #[inline]
  pub fn add_checksum(&mut self, checksum: u32) {
    self.fbb_.push_slot::<u32>(ManifestSstable::VT_CHECKSUM, checksum, 0);
  }
  #[inline]
  pub fn add_data_checksum(&mut self, data_checksum: u32) {
    self.fbb_.push_slot::<u32>(ManifestSstable::VT_DATA_CHECKSUM, data_checksum, 0);
  }
  #[inline]
  pub fn add_min_key(&mut self, min_key: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_MIN_KEY, min_key);
  }
  #[inline]
  pub fn add_max_key(&mut self, max_key: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_MAX_KEY, max_key);
  }
  #[inline]
  pub fn add_min_sequence(&mut self, min_sequence: u64) {
    self.fbb_.push_slot::<u64>(ManifestSstable::VT_MIN_SEQUENCE, min_sequence, 0);
  }
  #[inline]
  pub fn add_max_sequence(&mut self, max_sequence: u64) {
    self.fbb_.push_slot::<u64>(ManifestSstable::VT_MAX_SEQUENCE, max_sequence, 0);
  }
  #[inline]
  pub fn add_has_schema_version(&mut self, has_schema_version: bool) {
    self.fbb_.push_slot::<bool>(ManifestSstable::VT_HAS_SCHEMA_VERSION, has_schema_version, false);
  }
  #[inline]
  pub fn add_schema_version(&mut self, schema_version: u32) {
    self.fbb_.push_slot::<u32>(ManifestSstable::VT_SCHEMA_VERSION, schema_version, 0);
  }
  #[inline]
  pub fn add_shard_ownership_json(&mut self, shard_ownership_json: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestSstable::VT_SHARD_OWNERSHIP_JSON, shard_ownership_json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ManifestSstableBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ManifestSstableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ManifestSstable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ManifestSstable::VT_LOCAL_ID,"local_id");
    self.fbb_.required(o, ManifestSstable::VT_MIN_KEY,"min_key");
    self.fbb_.required(o, ManifestSstable::VT_MAX_KEY,"max_key");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ManifestSstable<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ManifestSstable");
      ds.field("table_id", &self.table_id());
      ds.field("level", &self.level());
      ds.field("local_id", &self.local_id());
      ds.field("file_path", &self.file_path());
      ds.field("remote_key", &self.remote_key());
      ds.field("length", &self.length());
      ds.field("checksum", &self.checksum());
      ds.field("data_checksum", &self.data_checksum());
      ds.field("min_key", &self.min_key());
      ds.field("max_key", &self.max_key());
      ds.field("min_sequence", &self.min_sequence());
      ds.field("max_sequence", &self.max_sequence());
      ds.field("has_schema_version", &self.has_schema_version());
      ds.field("schema_version", &self.schema_version());
      ds.field("shard_ownership_json", &self.shard_ownership_json());
      ds.finish()
  }
}
pub enum ManifestBodyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ManifestBody<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ManifestBody<'a> {
  type Inner = ManifestBody<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ManifestBody<'a> {
  pub const VT_FORMAT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_GENERATION: ::flatbuffers::VOffsetT = 6;
  pub const VT_LAST_FLUSHED_SEQUENCE: ::flatbuffers::VOffsetT = 8;
  pub const VT_SSTABLES: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ManifestBody { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ManifestBodyArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ManifestBody<'bldr>> {
    let mut builder = ManifestBodyBuilder::new(_fbb);
    builder.add_last_flushed_sequence(args.last_flushed_sequence);
    builder.add_generation(args.generation);
    if let Some(x) = args.sstables { builder.add_sstables(x); }
    builder.add_format_version(args.format_version);
    builder.finish()
  }


  #[inline]
  pub fn format_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestBody::VT_FORMAT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn generation(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ManifestBody::VT_GENERATION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn last_flushed_sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ManifestBody::VT_LAST_FLUSHED_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sstables(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ManifestSstable<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ManifestSstable>>>>(ManifestBody::VT_SSTABLES, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ManifestBody<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("format_version", Self::VT_FORMAT_VERSION, false)?
     .visit_field::<u64>("generation", Self::VT_GENERATION, false)?
     .visit_field::<u64>("last_flushed_sequence", Self::VT_LAST_FLUSHED_SEQUENCE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ManifestSstable>>>>("sstables", Self::VT_SSTABLES, true)?
     .finish();
    Ok(())
  }
}
pub struct ManifestBodyArgs<'a> {
    pub format_version: u32,
    pub generation: u64,
    pub last_flushed_sequence: u64,
    pub sstables: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ManifestSstable<'a>>>>>,
}
impl<'a> Default for ManifestBodyArgs<'a> {
  #[inline]
  fn default() -> Self {
    ManifestBodyArgs {
      format_version: 0,
      generation: 0,
      last_flushed_sequence: 0,
      sstables: None, // required field
    }
  }
}

pub struct ManifestBodyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ManifestBodyBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_format_version(&mut self, format_version: u32) {
    self.fbb_.push_slot::<u32>(ManifestBody::VT_FORMAT_VERSION, format_version, 0);
  }
  #[inline]
  pub fn add_generation(&mut self, generation: u64) {
    self.fbb_.push_slot::<u64>(ManifestBody::VT_GENERATION, generation, 0);
  }
  #[inline]
  pub fn add_last_flushed_sequence(&mut self, last_flushed_sequence: u64) {
    self.fbb_.push_slot::<u64>(ManifestBody::VT_LAST_FLUSHED_SEQUENCE, last_flushed_sequence, 0);
  }
  #[inline]
  pub fn add_sstables(&mut self, sstables: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ManifestSstable<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestBody::VT_SSTABLES, sstables);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ManifestBodyBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ManifestBodyBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ManifestBody<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ManifestBody::VT_SSTABLES,"sstables");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ManifestBody<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ManifestBody");
      ds.field("format_version", &self.format_version());
      ds.field("generation", &self.generation());
      ds.field("last_flushed_sequence", &self.last_flushed_sequence());
      ds.field("sstables", &self.sstables());
      ds.finish()
  }
}
pub enum ManifestFileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ManifestFile<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ManifestFile<'a> {
  type Inner = ManifestFile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ManifestFile<'a> {
  pub const VT_BODY_BYTES: ::flatbuffers::VOffsetT = 4;
  pub const VT_CHECKSUM: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ManifestFile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ManifestFileArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ManifestFile<'bldr>> {
    let mut builder = ManifestFileBuilder::new(_fbb);
    builder.add_checksum(args.checksum);
    if let Some(x) = args.body_bytes { builder.add_body_bytes(x); }
    builder.finish()
  }


  #[inline]
  pub fn body_bytes(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ManifestFile::VT_BODY_BYTES, None).unwrap()}
  }
  #[inline]
  pub fn checksum(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ManifestFile::VT_CHECKSUM, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ManifestFile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("body_bytes", Self::VT_BODY_BYTES, true)?
     .visit_field::<u32>("checksum", Self::VT_CHECKSUM, false)?
     .finish();
    Ok(())
  }
}
pub struct ManifestFileArgs<'a> {
    pub body_bytes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub checksum: u32,
}
impl<'a> Default for ManifestFileArgs<'a> {
  #[inline]
  fn default() -> Self {
    ManifestFileArgs {
      body_bytes: None, // required field
      checksum: 0,
    }
  }
}

pub struct ManifestFileBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ManifestFileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_body_bytes(&mut self, body_bytes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ManifestFile::VT_BODY_BYTES, body_bytes);
  }
  #[inline]
  pub fn add_checksum(&mut self, checksum: u32) {
    self.fbb_.push_slot::<u32>(ManifestFile::VT_CHECKSUM, checksum, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ManifestFileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ManifestFileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ManifestFile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ManifestFile::VT_BODY_BYTES,"body_bytes");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ManifestFile<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ManifestFile");
      ds.field("body_bytes", &self.body_bytes());
      ds.field("checksum", &self.checksum());
      ds.finish()
  }
}
}  // pub mod local_manifest
}  // pub mod durable
}  // pub mod terracedb

