// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod terracedb {

#[allow(unused_imports, dead_code)]
pub mod durable {

#[allow(unused_imports, dead_code)]
pub mod remote_cache {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_CACHE_SPAN_KIND: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_CACHE_SPAN_KIND: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_CACHE_SPAN_KIND: [CacheSpanKind; 3] = [
  CacheSpanKind::None,
  CacheSpanKind::Full,
  CacheSpanKind::Range,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct CacheSpanKind(pub u8);
#[allow(non_upper_case_globals)]
impl CacheSpanKind {
  pub const None: Self = Self(0);
  pub const Full: Self = Self(1);
  pub const Range: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Full,
    Self::Range,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Full => Some("Full"),
      Self::Range => Some("Range"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for CacheSpanKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for CacheSpanKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for CacheSpanKind {
    type Output = CacheSpanKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for CacheSpanKind {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for CacheSpanKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for CacheSpanKind {}
pub enum RemoteCacheEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RemoteCacheEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RemoteCacheEntry<'a> {
  type Inner = RemoteCacheEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RemoteCacheEntry<'a> {
  pub const VT_FORMAT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_OBJECT_KEY: ::flatbuffers::VOffsetT = 6;
  pub const VT_SPAN_KIND: ::flatbuffers::VOffsetT = 8;
  pub const VT_START: ::flatbuffers::VOffsetT = 10;
  pub const VT_END: ::flatbuffers::VOffsetT = 12;
  pub const VT_DATA_LEN: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RemoteCacheEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RemoteCacheEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RemoteCacheEntry<'bldr>> {
    let mut builder = RemoteCacheEntryBuilder::new(_fbb);
    builder.add_data_len(args.data_len);
    builder.add_end(args.end);
    builder.add_start(args.start);
    if let Some(x) = args.object_key { builder.add_object_key(x); }
    builder.add_format_version(args.format_version);
    builder.add_span_kind(args.span_kind);
    builder.finish()
  }


  #[inline]
  pub fn format_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(RemoteCacheEntry::VT_FORMAT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn object_key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RemoteCacheEntry::VT_OBJECT_KEY, None).unwrap()}
  }
  #[inline]
  pub fn span_kind(&self) -> CacheSpanKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<CacheSpanKind>(RemoteCacheEntry::VT_SPAN_KIND, Some(CacheSpanKind::None)).unwrap()}
  }
  #[inline]
  pub fn start(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RemoteCacheEntry::VT_START, Some(0)).unwrap()}
  }
  #[inline]
  pub fn end(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RemoteCacheEntry::VT_END, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data_len(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RemoteCacheEntry::VT_DATA_LEN, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RemoteCacheEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("format_version", Self::VT_FORMAT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("object_key", Self::VT_OBJECT_KEY, true)?
     .visit_field::<CacheSpanKind>("span_kind", Self::VT_SPAN_KIND, false)?
     .visit_field::<u64>("start", Self::VT_START, false)?
     .visit_field::<u64>("end", Self::VT_END, false)?
     .visit_field::<u64>("data_len", Self::VT_DATA_LEN, false)?
     .finish();
    Ok(())
  }
}
pub struct RemoteCacheEntryArgs<'a> {
    pub format_version: u32,
    pub object_key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub span_kind: CacheSpanKind,
    pub start: u64,
    pub end: u64,
    pub data_len: u64,
}
impl<'a> Default for RemoteCacheEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    RemoteCacheEntryArgs {
      format_version: 0,
      object_key: None, // required field
      span_kind: CacheSpanKind::None,
      start: 0,
      end: 0,
      data_len: 0,
    }
  }
}

pub struct RemoteCacheEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RemoteCacheEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_format_version(&mut self, format_version: u32) {
    self.fbb_.push_slot::<u32>(RemoteCacheEntry::VT_FORMAT_VERSION, format_version, 0);
  }
  #[inline]
  pub fn add_object_key(&mut self, object_key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RemoteCacheEntry::VT_OBJECT_KEY, object_key);
  }
  #[inline]
  pub fn add_span_kind(&mut self, span_kind: CacheSpanKind) {
    self.fbb_.push_slot::<CacheSpanKind>(RemoteCacheEntry::VT_SPAN_KIND, span_kind, CacheSpanKind::None);
  }
  #[inline]
  pub fn add_start(&mut self, start: u64) {
    self.fbb_.push_slot::<u64>(RemoteCacheEntry::VT_START, start, 0);
  }
  #[inline]
  pub fn add_end(&mut self, end: u64) {
    self.fbb_.push_slot::<u64>(RemoteCacheEntry::VT_END, end, 0);
  }
  #[inline]
  pub fn add_data_len(&mut self, data_len: u64) {
    self.fbb_.push_slot::<u64>(RemoteCacheEntry::VT_DATA_LEN, data_len, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RemoteCacheEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RemoteCacheEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RemoteCacheEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, RemoteCacheEntry::VT_OBJECT_KEY,"object_key");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RemoteCacheEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RemoteCacheEntry");
      ds.field("format_version", &self.format_version());
      ds.field("object_key", &self.object_key());
      ds.field("span_kind", &self.span_kind());
      ds.field("start", &self.start());
      ds.field("end", &self.end());
      ds.field("data_len", &self.data_len());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `RemoteCacheEntry`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_remote_cache_entry_unchecked`.
pub fn root_as_remote_cache_entry(buf: &[u8]) -> Result<RemoteCacheEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<RemoteCacheEntry>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RemoteCacheEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_remote_cache_entry_unchecked`.
pub fn size_prefixed_root_as_remote_cache_entry(buf: &[u8]) -> Result<RemoteCacheEntry<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<RemoteCacheEntry>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RemoteCacheEntry` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_remote_cache_entry_unchecked`.
pub fn root_as_remote_cache_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RemoteCacheEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<RemoteCacheEntry<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RemoteCacheEntry` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_remote_cache_entry_unchecked`.
pub fn size_prefixed_root_as_remote_cache_entry_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RemoteCacheEntry<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<RemoteCacheEntry<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RemoteCacheEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RemoteCacheEntry`.
pub unsafe fn root_as_remote_cache_entry_unchecked(buf: &[u8]) -> RemoteCacheEntry<'_> {
  unsafe { ::flatbuffers::root_unchecked::<RemoteCacheEntry>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RemoteCacheEntry and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RemoteCacheEntry`.
pub unsafe fn size_prefixed_root_as_remote_cache_entry_unchecked(buf: &[u8]) -> RemoteCacheEntry<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<RemoteCacheEntry>(buf) }
}
pub const REMOTE_CACHE_ENTRY_IDENTIFIER: &str = "TDRC";

#[inline]
pub fn remote_cache_entry_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, REMOTE_CACHE_ENTRY_IDENTIFIER, false)
}

#[inline]
pub fn remote_cache_entry_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, REMOTE_CACHE_ENTRY_IDENTIFIER, true)
}

#[inline]
pub fn finish_remote_cache_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<RemoteCacheEntry<'a>>) {
  fbb.finish(root, Some(REMOTE_CACHE_ENTRY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_remote_cache_entry_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<RemoteCacheEntry<'a>>) {
  fbb.finish_size_prefixed(root, Some(REMOTE_CACHE_ENTRY_IDENTIFIER));
}
}  // pub mod remote_cache
}  // pub mod durable
}  // pub mod terracedb

