// @generated by cargo run -p terracedb-sandbox --bin generate_node_upstream_tests

pub const GENERATED_UPSTREAM_NODE_CASES: &[node_compat::GeneratedUpstreamNodeCase] = &[
    node_compat::GeneratedUpstreamNodeCase::new(
        "test-module-builtin",
        "/test/parallel/test-module-builtin.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-module-create-require",
        "/test/parallel/test-module-create-require.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-module-nodemodulepaths",
        "/test/parallel/test-module-nodemodulepaths.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-module-wrapper",
        "/test/parallel/test-module-wrapper.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-require-cache",
        "/test/parallel/test-require-cache.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-require-dot",
        "/test/parallel/test-require-dot.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-require-node-prefix",
        "/test/parallel/test-require-node-prefix.js",
        30,
    ),

    node_compat::GeneratedUpstreamNodeCase::new(
        "test-require-resolve",
        "/test/parallel/test-require-resolve.js",
        30,
    ),

];
