// @generated by cargo run -p terracedb-sandbox --bin generate_node_upstream_tests
#[path = "../support/node_compat.rs"]
mod node_compat;

fn stdout_stderr_exit(result: &terracedb_sandbox::SandboxExecutionResult) -> (String, String, i64) {
    let report = result
        .result
        .as_ref()
        .and_then(|value| value.as_object())
        .expect("node command report");
    let stdout = report
        .get("stdout")
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .to_string();
    let stderr = report
        .get("stderr")
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .to_string();
    let exit_code = report
        .get("exitCode")
        .and_then(|value| value.as_i64())
        .unwrap_or_default();
    (stdout, stderr, exit_code)
}

include!("body.rs");
