use crate::{ActorId, JsCompileError, JsRuntimeId, WorkerId};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Error {
    ActorNotFound { actor: ActorId },
    ActorMessageTypeMismatch,
    ActorRegistryPoisoned,
    ActorReplyTypeMismatch,
    CompioRuntimeInit { worker: WorkerId, source: String },
    HostReplyClosed,
    InvalidWorkerIndex { worker: usize },
    JsAssignToConst { name: String },
    JsBindingNotFound { name: String },
    JsCannotPopRootScope,
    JsCompile(JsCompileError),
    JsDuplicateBinding { name: String },
    JsIdentifierNotFound { name: String },
    JsInstructionPointerOutOfBounds { ip: usize },
    JsInvalidConstant { id: u32 },
    JsInvalidConsoleCall,
    JsInvalidOperand,
    JsStackUnderflow,
    JsTypeError { message: String },
    MissingConsole,
    MissingSimulationSeed,
    MissingSimulationWorkerCount,
    NoCores,
    NoWorkers,
    OutputReceiverDropped,
    PinFailed { worker: WorkerId },
    ReentrantActorCall { actor: ActorId },
    RuntimeNotFound(JsRuntimeId),
    ThreadPanicked,
    ThreadSpawn { worker: WorkerId, source: String },
    WorkerInboxClosed,
    WorkerInitChannelClosed,
    WorkerSubmit,
}
